first/envvuproject/cristal/urls.py
from . import views
from django.urls import path

app_name = 'cristal'
urlpatterns = [
    path('', views.index, name='index'),
    path('introduction/',views.introduction,name='introduction'),
    path('management/',views.management,name='management'),
    path('directors-message/', views.directormessage, name='directormessage'),
    path('corecompetence/', views.corecompetence, name='corecompetence'),
    path('our-team/',views.ourteam,name='ourteam'),
    path('classIX/',views.classIX,name='classIX'),
    path('classX/',views.classX,name='classX'),
    path('classXI/', views.classXI, name='classXI'),
    path('classXII/', views.classXII, name='classXII'),
    path('classXII-pass/', views.classXIIpass, name='classXIIpass'),
    path('ibs-bank-coaching/', views.ibsbankcoaching, name='ibsbankcoaching'),
    path('result-19-20/', views.result19_20, name='result19_20'),
    path('result-18-19/', views.result18_19, name='result18_19'),
    path('result-17-18/', views.result17_18, name='result17_18'),
    path('result-16-17/', views.result16_17, name='result16_17'),
    path('result-15-16/', views.result15_16, name='result15_16'),
    path('result-14-15/', views.result14_15, name='result14_15'),
    path('result-13-14/', views.result13_14, name='result13_14'),
    path('result-12-13/', views.result12_13, name='result12_13'),
    path('result-11-12/', views.result11_12, name='result11_12'),
    path('contactus/', views.contactus, name='contactus'),



    path('regnform/', views.regnform, name='regnform'),
    path('testimonials/', views.testimonials, name='testimonials'),
    path('online-regnform-tutions/', views.online_regnform_tutions, name='online_regnform_tutions'),
    path('terms-and-conditions/',views.terms_and_conditions,name='terms_and_conditions'),
    path('refund-policy/',views.refund_policy,name='refund_policy'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
]

first/envvuproject/envvuproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cristal.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

first/envvuproject/cristal/models.py
from django.db import models

# Create your models here.

first/envvuproject/cristal/views.py
from django.shortcuts import render

from django.core.mail import send_mail
from django.http import HttpResponse



# Create your views here.

def index(request):
    return render(request, "index.html")


def introduction(request):
    return render(request, "introduction.html")


def management(request):
    return render(request, "management.html")


def directormessage(request):
    return render(request, "directors_msg.html")


def corecompetence(request):
    return render(request, "corecompetence.html")


def ourteam(request):
    return render(request, "ourteam.html")


def classIX(request):
    return render(request, "classIX.html")


def classX(request):
    return render(request, "classX.html")


def classXI(request):
    return render(request, "classXI.html")


def classXII(request):
    return render(request, "classXII.html")


def classXIIpass(request):
    return render(request, "classXIIpass.html")


def ibsbankcoaching(request):
    return render(request, "ibs-bank-coaching.html")


def result19_20(request):
    return render(request, "result-19-20.html")


def result18_19(request):
    return render(request, "result-18-19.html")


def result17_18(request):
    return render(request, "result-17-18.html")


def result16_17(request):
    return render(request, "result-16-17.html")


def result15_16(request):
    return render(request, "result-15-16.html")


def result14_15(request):
    return render(request, "result-14-15.html")


def result13_14(request):
    return render(request, "result-13-14.html")


def result12_13(request):
    return render(request, "result-12-13.html")


def result11_12(request):
    return render(request, "result-11-12.html")


def contactus(request):
    return render(request, "contactus.html")


def regnform(request):
    return render(request, "regnform.html")


def online_regnform_tutions(request):
    return render(request, "online_regnform_tutions.html")

def testimonials(request):
    return render(request,"testimonials.html")


def terms_and_conditions(request):
    return render(request, "terms_and_conditions.html")


def refund_policy(request):
    return render(request, "refund-policy.html")


def privacy_policy(request):
    return render(request, "privacy-policy.html")


def home_2(request):
    return render(request,"home_2.html")



'''def contact(request):
    if request.method=='POST':
        name=request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        message = request.POST['message']

        template = get_template('contactus2.txt')
        context = {'name':name,'email':email,'phone':phone,'message':message}
        content = template.render(context)
        email = EmailMessage(
            "contact from recieved",
            content,
            "contact from "+'',
            ['envvumarketing3@gmail.com','envvumarketing6@gmail.com'],
            headers = {'Reply to ':email}

        )
        email.send()
        messages.success(request,+'thank you for contacting us')
    return render(request,'contactus.html')'''


def contactus(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')


        data = {
            'name': name,
            'email': email,
            'phone': phone,
            'message': message,
        }
        print(data)

        message = '''

         Name: {}

         Email: {}

         phone: {}

         message: {}

        '''.format(data['name'], data['email'], data['phone'], data['message'])
        send_mail('ENQUIRY', message, '',
                  ['envvumarketing6@gmail.com','envvumarketing3@gmail.com'])

        html = "<html><body><br><br><h2>ThankYou For Submitting Registration form.</h2></body></html>"
        return HttpResponse(html)

    return render(request, "contactus.html", {})

first/envvuproject/templates/home_2.html
{% load static %}
<!doctype html>
<html lang="en">

	<!-- Google Web Fonts
	================================================== -->

	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">

	<!-- Basic Page Needs
	================================================== -->

	<title>  </title>
    
<!-- Mirrored from newcristalacademy.com/testimonials/home_2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 12:13:42 GMT -->
<meta charset="utf-8">
	<meta name="author" content="">
	<meta name="keywords" content="">
	<meta name="description" content="">

	<!-- Mobile Specific Metas
	================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	<!-- CSS theme files
	============================================ -->
	<link rel="stylesheet" href="css/owl.carousel.css">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/responsive.css">

</head>

<body>

  <div class="loader"></div>

  <!--cookie-->
  <!-- <div class="cookie">
          <div class="container">
            <div class="clearfix">
              <span>Please note this website requires cookies in order to function correctly, they do not store any specific information about you personally.</span>
              <div class="f-right"><a href="#" class="button button-type-3 button-orange">Accept Cookies</a><a href="#" class="button button-type-3 button-grey-light">Read More</a></div>
            </div>
          </div>
        </div>-->

  <!-- - - - - - - - - - - - - - Wrapper - - - - - - - - - - - - - - - - -->

  <div id="wrapper" class="wrapper-container">

  
    <div id="content">

        
        
	<div class="section-with-carousel with-bg parallax-section">

	        <div class="comment-section align-center">

	        	<div class="container">
	        		
	        		<h2 class="section-title text-uppercase" style="text-transform:uppercase;font-family:font-family: 'Montserrat', sans-serif;font-weight:700;font-size: 31px;">Testimonials</h2>

	    			<!-- - - - - - - - - - - - - Owl-Carousel - - - - - - - - - - - - - - - -->

		          	<div class="carousel-type-1">

			          	<div class="owl-carousel testimonial type-2" data-max-items="3" data-item-margin="30" data-autoplay="true">

			          		<!-- Slide -->				          
			          		<div class="item-carousel">
			          			<!-- Carousel Item -->
			          			
			          			<div class="comment-item">
			          				
			          				<div class="comment-holder">
			          					
			          					<blockquote>
					                      	<p>“Cristal academy is one of the best coaching centre with best teaching faculty. Thank you so much for 
giving me such a wonderful learning experience and more knowledge which helped me to brighten my future.”</p>
					                    </blockquote>

			          				</div>

			          				<!-- bottom-separator -->
									<div class="bottom-separator"></div>

			          			</div>

			          			<div class="author-box">

				                    <a href="#" class="avatar">
				                      <img src="../dashboard/testimonial/1490097395sreehari.jpg" alt="">
				                    </a>

				                    <div class="author-info">

				                      <span class="author-name">SREEHARI R</span>

				                    </div>

				                </div>

			          			<!-- /Carousel Item --> 
			          		</div>
			          		<!-- /Slide -->

			          						          <!-- Slide -->				          
			          		<div class="item-carousel">
			          			<!-- Carousel Item -->
			          			
			          			<div class="comment-item">
			          				
			          				<div class="comment-holder">
			          					
			          					<blockquote>
					                      	<p>“Action speaks louder than words<br />
The only institute in Palakkad to produce IIT qualifiers in successive years.
Unique qualities of Cristal academy are vibrant panel of teachers who are highly qualified in their streams spacious classrooms, spacious library, homely atmosphere, any time doubt clearance bench etc.”</p>
					                    </blockquote>

			          				</div>

			          				<!-- bottom-separator -->
									<div class="bottom-separator"></div>

			          			</div>

			          			<div class="author-box">

				                    <a href="#" class="avatar">
				                      <img src="../error.html" alt="">
				                    </a>

				                    <div class="author-info">

				                      <span class="author-name">NIHALA NAZRIN A A</span>

				                    </div>

				                </div>

			          			<!-- /Carousel Item --> 
			          		</div>
			          		<!-- /Slide -->

			          		<!-- Slide -->				          
			          		<div class="item-carousel">
			          			<!-- Carousel Item -->
			          			
			          			<div class="comment-item">
			          				
			          				<div class="comment-holder">
			          					
			          					<blockquote>
					                      	<p>“The ladder to success – Cristal Academy
Helps the children to make their dream come true
Efficient faculties to give all time support
Good library support which helps students to bring their confidence level to better height
Motivates and guides to achieve the ultimate aim.”</p>
					                    </blockquote>

			          				</div>

			          				<!-- bottom-separator -->
									<div class="bottom-separator"></div>

			          			</div>

			          			<div class="author-box">

				                    <a href="#" class="avatar">
				                      <img src="../dashboard/testimonial/1490272986vandana.jpg" alt="">
				                    </a>

				                    <div class="author-info">

				                      <span class="author-name">VANDANA O</span>

				                    </div>

				                </div>

			          			<!-- /Carousel Item --> 
			          		</div>
			          		<!-- /Slide -->

			          		<!-- Slide -->				          
			          		<div class="item-carousel">
			          			<!-- Carousel Item -->
			          			
			          			<div class="comment-item">
			          				
			          				<div class="comment-holder">
			          					
			          					<blockquote>
					                      	<p>“The best Coaching institute in Palakkad ever with a very systematic way of teaching which helps the students to face the entrance exam with confidence. I am proud to be a part of this institution as it played a very important role in moulding my future.”</p>
					                    </blockquote>

			          				</div>

			          				<!-- bottom-separator -->
									<div class="bottom-separator"></div>

			          			</div>

			          			<div class="author-box">

				                    <a href="#" class="avatar">
				                      <img src="../dashboard/testimonial/1490096733sreelakshmi.jpg" alt="">
				                    </a>

				                    <div class="author-info">

				                      <span class="author-name">Sreelakshmi P</span>

				                    </div>

				                </div>

			          			<!-- /Carousel Item --> 
			          		</div>
			          		<!-- /Slide -->

			          						          <!-- Slide -->			
			          	</div>

			        </div>
			        
			        
					<!--<a href="{% url 'cristal:testimonials' %}" target="_top" class="btn btn-default center-block">Read More</a>-->

	        	</div>

    		</div>
	        
	    </div>



    </div>

  </div>

  <!-- - - - - - - - - - - - end Wrapper - - - - - - - - - - - - - - -->

  <!-- JS Libs & Plugins
  ============================================ -->
  <script src="js/libs/jquery.modernizr.js"></script>
  <script src="js/libs/jquery-2.2.4.min.js"></script>
  <script src="js/libs/jquery-ui.min.js"></script>
  <script src="js/libs/retina.min.js"></script>
  <script src="plugins/owl.carousel.min.js"></script>
  <script src="plugins/jquery.queryloader2.min.js"></script>

  <!-- JS theme files
  ============================================ -->
  <script src="js/plugins.js"></script>
  <script src="js/script.js"></script>
  
</body>

<!-- Mirrored from velikorodnov.com/html/owlhouse/home_2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 12 Apr 2017 06:25:42 GMT -->

<!-- Mirrored from newcristalacademy.com/testimonials/home_2.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Aug 2021 12:14:13 GMT -->
</html>